/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Model.Enterprise.Enterprise;
import Model.Network.Network;
import Model.Network.NetworkDirectory; // Corrected import
import Model.Organization.Organization;
import Model.Role.Role;
import Model.User.UserAccount;
import Model.ConfigureASystem; // For initializing the system data
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField; // For handling password input

// Import specific role classes for type checking
import Model.Personnel.Admin;
import Model.Personnel.Doctor;
import Model.Personnel.Nurse;
import Model.Personnel.EmergencyDispatcher;
import Model.Personnel.EmergencyResponder;
import Model.Personnel.LogisticsManager;
import Model.Personnel.DeliveryStaff;
import Model.Personnel.DonationCoordinator;
import Model.Personnel.PayrollStaff;
import Model.Personnel.Manager;
import Model.Personnel.ResourceAnalyst;
import Model.Personnel.Visitor;
import Model.Role.AdminRole;
import Model.Role.DeliveryStaffRole;
import Model.Role.DoctorRole;
import Model.Role.DonationCoordinatorRole;
import Model.Role.EmergencyDispatcherRole;
import Model.Role.EmergencyResponderRole;
import Model.Role.LogisticsManagerRole;
import Model.Role.NurseRole;
import Model.Role.PayrollStaffRole;
import Model.Role.VisitorRole;
import java.awt.CardLayout;
import ui.DeliveryStaff.DeliveryStaffWorkAreaPanel;
import ui.DonationCoordinator.DonationCoordinatorWorkAreaPanel;
import ui.EmergencyDispatcher.EmergencyDispatcherWorkAreaPanel;
import ui.EmergencyResponder.EmergencyResponderWorkAreaPanel;
import ui.EquipmentTechnician.EquipmentTechnicianWorkAreaPanel;
import ui.HospitalDoctor.HospitalDoctorWorkAreaPanel;
import ui.HospitalNurse.HospitalNurseWorkArea;
import ui.PayrollOfficer.PayrollOfficerWorkAreaPanel;
import ui.SupplychainManager.SupplyOfficerWorkAreaPanel;
import ui.VisitorDonor.VisitorDonorWorkAreaPanel;

/**
 *
 * @author tiankaining
 */
public class MainJFrame extends javax.swing.JFrame {

    private NetworkDirectory system;
    private JPanel userProcessContainer;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setResizable(false);
        this.setSize(1000, 800);
        this.system = ConfigureASystem.configure(); 
        this.userProcessContainer = jPanel2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(loginBtn)
                            .addComponent(logoutBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(loginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutBtn)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Medica Crisis Communication System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel1)
                .addContainerGap(536, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {
        txtUsername.setText("");
        ((JPasswordField)txtPassword).setText(""); 
        jSplitPane1.setRightComponent(jPanel2);
    }

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String username = txtUsername.getText();
        String password = txtPassword.getText();

        UserAccount authenticatedUser = null;
        Network currentNetwork = null;
        Enterprise currentEnterprise = null;
        Organization currentOrg = null;

        // 1. 系统级查找
        authenticatedUser = system.getUserAccountDirectory().authenticateUser(username, password);

        // 2. 逐层递归查找用户（Network → Enterprise → Organization）
        if (authenticatedUser == null) {
            for (Network network : system.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    // Enterprise 层找
                    Admin admin = enterprise.getAdmin();
                    if (admin != null &&
                        admin.getUsername().equals(username) &&
                        admin.getPassword().equals(password)) {
                        authenticatedUser = admin;  // 注意类型
                        currentEnterprise = enterprise;
                        break;
                    }

                    // Organization 层找
                    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        authenticatedUser = org.getUserAccountDirectory().authenticateUser(username, password);
                        if (authenticatedUser != null) {
                            currentNetwork = network;
                            currentEnterprise = enterprise;
                            currentOrg = org;
                            break;
                        }
                    }

                    if (authenticatedUser != null) break;
                }

                if (authenticatedUser != null) break;
            }
        }

        // 3. 没找到：提示错误
        if (authenticatedUser == null) {
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
            return;
        }

        // 4. 获取角色
        Role role = authenticatedUser.getRole();
        JPanel workAreaPanel = null;

        // 5. 分流：按角色分配界面
        if (role instanceof AdminRole) {
            if (currentOrg != null) {
                // Organization Admin → 用户管理
                workAreaPanel = new ManageUserAccounts(userProcessContainer, currentOrg);
            } else if (currentEnterprise != null) {
                // Enterprise Admin → 组织管理
                workAreaPanel = new ManageOrganization(userProcessContainer, currentEnterprise.getOrganizationDirectory(), currentEnterprise);
            } else if (currentNetwork != null) {
                // Network Admin → 企业管理
                workAreaPanel = new ManageEnterprise(userProcessContainer, currentNetwork);
            } else {
                JOptionPane.showMessageDialog(this, "Admin context missing.");
                return;
            }

        } else if (role instanceof EmergencyDispatcherRole) {
            workAreaPanel = new EmergencyDispatcherWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof EmergencyResponderRole) {
            workAreaPanel = new EmergencyResponderWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof DoctorRole) {
            workAreaPanel = new HospitalDoctorWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof NurseRole) {
            workAreaPanel = new HospitalNurseWorkArea(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof LogisticsManagerRole) {
            workAreaPanel = new SupplyOfficerWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof DonationCoordinatorRole) {
            workAreaPanel = new DonationCoordinatorWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof PayrollStaffRole) {
            workAreaPanel = new PayrollOfficerWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof DeliveryStaffRole) {
            workAreaPanel = new DeliveryStaffWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } else if (role instanceof VisitorRole) {
            workAreaPanel = new VisitorDonorWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
        } 
//        else if (role instanceof ResourceAnalystRole) {
//            workAreaPanel = new EquipmentTechnicianWorkAreaPanel(userProcessContainer, currentOrg, authenticatedUser);
//        } 
        else {
            JOptionPane.showMessageDialog(this, "Unrecognized role type.");
            return;
        }

        // 6. 跳转到对应工作界面
        userProcessContainer.add("workAreaPanel", workAreaPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);   
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
