/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DonationCoordinator;

import Model.Organization.Organization;
import Model.Supplies.DonationCatalog;
import Model.User.UserAccount;
import javax.swing.JPanel;
import ui.VisitorDonor.*;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import Model.Supplies.Donation;
import Model.Supplies.DonatedItem;

/**
 *
 * @author tiankaining
 */
public class ViewDonationHistory extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;
    private DonationCatalog donationCatalog; // List of donations to display

    public ViewDonationHistory(JPanel userProcessContainer, Organization organization, UserAccount userAccount, DonationCatalog donationCatalog) {
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.userAccount = userAccount;
        this.donationCatalog = donationCatalog;
        initComponents();
        
        // 添加业务逻辑初始化
        populateDonationHistoryTable();
    }
    
    private void populateDonationHistoryTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewDonationHistory.getModel();
        model.setRowCount(0);

        for (Donation donation : donationCatalog.getDonationList()) {
            String description = "";
            if (donation.getAmount() > 0) {
                description = "Monetary: $" + donation.getAmount();
            } else {
                description = "Items: " + donation.getDonatedItems().size() + " item(s)";
            }

            Object[] row = {
                donation.getDonationId(),
                donation.getDonor().getName(),
                description,
                donation.getAmount() > 0 ? "$" + donation.getAmount() : 
                    donation.getDonatedItems().size() + " items"
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewDonationHistory = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("View Donation History");

        btnViewDetail.setText("View Detail");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblViewDonationHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Donation ID", "Donor Name", "Donation Description", "Amount/Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewDonationHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(377, 377, 377))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(88, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 494, Short.MAX_VALUE)
                .addComponent(btnViewDetail)
                .addGap(208, 208, 208))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(111, 111, 111)
                    .addComponent(btnBack)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
    int selectedRow = tblViewDonationHistory.getSelectedRow();
        
        String donationId = (String) tblViewDonationHistory.getValueAt(selectedRow, 0);
        Donation donation = donationCatalog.findDonationById(donationId);

        StringBuilder details = new StringBuilder();
        details.append("Donation ID: ").append(donation.getDonationId()).append("\n");
        details.append("Donor: ").append(donation.getDonor().getName()).append("\n");
        details.append("Date: ").append(donation.getDonationDate()).append("\n");
        details.append("Purpose: ").append(donation.getPurpose()).append("\n");
        details.append("Status: ").append(donation.getStatus()).append("\n");
        
        if (donation.getAmount() > 0) {
            details.append("Amount: $").append(donation.getAmount()).append("\n");
        } else {
            details.append("Items:\n");
            for (DonatedItem item : donation.getDonatedItems()) {
                details.append("  - ").append(item.getName())
                       .append(" (Qty: ").append(item.getQuantity()).append(")\n");
            }
        }
        
        details.append("Notes: ").append(donation.getNotes()).append("\n");

        JOptionPane.showMessageDialog(this, details.toString(), "Donation Details", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewDonationHistory;
    // End of variables declaration//GEN-END:variables
}
