/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HospitalNurse;

import Model.Organization.ClinicalServicesUnit;
import Model.Patient.CarePlanData;
import Model.Patient.Patient;
import Model.Patient.PatientDirectory;
import Model.User.UserAccount;
import Model.Personnel.Nurse;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;


/**
 *
 * @author tiankaining
 */
public class ManagePatientCarePlans extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ClinicalServicesUnit organization;
    private UserAccount userAccount;
    private PatientDirectory patientDirectory;
    private Map<String, CarePlanData> carePlansMap;

    // NetBeans 默认构造函数（可选，建议保留仅在 GUI builder 用）
    public ManagePatientCarePlans() {
        initComponents();
    }

    // 推荐使用的业务构造函数
    public ManagePatientCarePlans(JPanel userProcessContainer, ClinicalServicesUnit organization, 
                                UserAccount userAccount, PatientDirectory patientDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.userAccount = userAccount;
        this.patientDirectory = patientDirectory;
        this.carePlansMap = new HashMap<>();
        
        
        initComponents();
        initializeData();
    }
    
        private void initializeData() {
        // 设置负责护士下拉框
        String[] nurses = {"Alice Johnson", "Bob Smith", "Carol White", "David Brown", "Eva Green"};
        
        CmbcreateResponsibleNurse.removeAllItems();
        CmbviewResponsibleNurse.removeAllItems();
        
        for (String nurse : nurses) {
            CmbcreateResponsibleNurse.addItem(nurse);
            CmbviewResponsibleNurse.addItem(nurse);
        }
        
        
        // 填充表格数据
        populateCarePlansTable();
        
        // 为表格添加选择监听器
        tblPatientCarePlans.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                btnViewDetailsActionPerformed(null);
            }
        });
    }

    private void populateCarePlansTable() {
        DefaultTableModel model = (DefaultTableModel) tblPatientCarePlans.getModel();
        model.setRowCount(0); // 清空现有数据
        
        // 设置正确的列标题
        model.setColumnIdentifiers(new String[]{
            "Patient ID", "Patient Name", "Assigned Nurse", "Risk Level", "Start Date"
        });
        
        // 填充护理计划数据
        for (CarePlanData plan : carePlansMap.values()) {
            model.addRow(new Object[]{
                plan.getPatient().getPatientId(),
                plan.getPatient().getName(),
                plan.getResponsibleNurse(),
                plan.getRiskLevel(),
                plan.getStartDate()
            });
        }
            // Populate dummy data if the map is empty
    if (carePlansMap.isEmpty()) {
        Patient dummyPatient = patientDirectory.createPatient("John Doe", "Male", 35, "2025-06-06");
        CarePlanData dummyPlan = new CarePlanData(dummyPatient, "2025-06-06", 
                                                  "Alice Johnson", "High", "Low sodium", "Daily bath");
        carePlansMap.put(dummyPatient.getPatientId(), dummyPlan);
    }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtviewCarePlanStartDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcreateRiskLevel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtviewRiskLevel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtviewHygieneNeeds = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        txtcreateHygieneNeeds = new javax.swing.JTextField();
        txtcreateCarePlanStartDate = new javax.swing.JTextField();
        txtcreateDietaryNeeds = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        txtviewPatientName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcreatePatientName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CmbcreateResponsibleNurse = new javax.swing.JComboBox<>();
        btnExportToCSV = new javax.swing.JButton();
        txtviewDietaryNeeds = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientCarePlans = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        CmbviewResponsibleNurse = new javax.swing.JComboBox<>();

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("Hygiene Needs:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("Risk Level:");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Manage Patient Care Plans");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel15.setText("Risk Level:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Dietary Needs:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Responsible Nurse:");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel16.setText("View Details:");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel14.setText("Dietary Needs:");

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setText("View Patient Care Plans:");

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Create Report:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Hygiene Needs:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Patient Name:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Care Plan Start Date:");

        CmbcreateResponsibleNurse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnExportToCSV.setText("Export to csv");
        btnExportToCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportToCSVActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Patient Name:");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel13.setText("Responsible Nurse:");

        tblPatientCarePlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Assigned Nurse", "Risk Level:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatientCarePlans);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Care Plan Start Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnViewDetails))
                                                    .addGap(81, 81, 81)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnExportToCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtcreatePatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtcreateDietaryNeeds, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtcreateHygieneNeeds, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtcreateRiskLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtcreateCarePlanStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(CmbcreateResponsibleNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(266, 266, 266)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtviewDietaryNeeds)
                                            .addComponent(txtviewHygieneNeeds, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(txtviewRiskLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(81, 81, 81))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(52, 52, 52)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtviewCarePlanStartDate)
                                            .addComponent(CmbviewResponsibleNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtviewPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(332, 332, 332))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnExportToCSV)
                    .addComponent(btnViewDetails))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtviewPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcreatePatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtviewCarePlanStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(CmbviewResponsibleNurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtviewRiskLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtviewDietaryNeeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtviewHygieneNeeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcreateCarePlanStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CmbcreateResponsibleNurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcreateRiskLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcreateDietaryNeeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcreateHygieneNeeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate)
                    .addComponent(btnModify))
                .addGap(25, 25, 25)
                .addComponent(btnBack)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
int selectedRow = tblPatientCarePlans.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, 
        "Please select a care plan to delete first.", "No Selection", JOptionPane.WARNING_MESSAGE);
    return;
}

int choice = JOptionPane.showConfirmDialog(this,
    "Are you sure you want to delete the selected care plan?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

if (choice == JOptionPane.YES_OPTION) {
    try {
        String patientId = (String) tblPatientCarePlans.getValueAt(selectedRow, 0);
        carePlansMap.remove(patientId);

        populateCarePlansTable();
        clearViewFields();

        JOptionPane.showMessageDialog(this, 
            "Care plan deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "An error occurred while deleting the care plan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            // 获取输入数据
            String patientName = txtcreatePatientName.getText().trim();
            String startDate = txtcreateCarePlanStartDate.getText().trim();
            String responsibleNurse = (String) CmbcreateResponsibleNurse.getSelectedItem();
            String riskLevel = txtcreateRiskLevel.getText().trim();
            String dietaryNeeds = txtcreateDietaryNeeds.getText().trim();
            String hygieneNeeds = txtcreateHygieneNeeds.getText().trim();
            
            // 验证输入
            if (patientName.isEmpty() || startDate.isEmpty() || 
                responsibleNurse == null || responsibleNurse.trim().isEmpty() ||
                riskLevel.isEmpty() || dietaryNeeds.isEmpty() || hygieneNeeds.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Please fill in all required fields", "Input error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Find patient
Patient patient = patientDirectory.findPatientByName(patientName);
if (patient == null) {
    int choice = JOptionPane.showConfirmDialog(this,
        "Patient does not exist. Would you like to create a new patient?", "Confirmation", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        patient = patientDirectory.createPatient(patientName, "Unknown", 0, startDate);
    } else {
        return;
    }
}

// Check if patient already has a care plan
if (carePlansMap.containsKey(patient.getPatientId())) {
    JOptionPane.showMessageDialog(this, 
        "This patient already has a care plan. Please use the edit function.", "Duplicate Plan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Create care plan
CarePlanData carePlan = new CarePlanData(patient, startDate, responsibleNurse, 
                                         riskLevel, dietaryNeeds, hygieneNeeds);
carePlansMap.put(patient.getPatientId(), carePlan);

// Refresh table
populateCarePlansTable();

// Clear input fields
clearCreateFields();

JOptionPane.showMessageDialog(this, 
    "Care plan created successfully!\nPlan ID: " + carePlan.getPlanId(), 
    "Success", JOptionPane.INFORMATION_MESSAGE);

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, 
        "An error occurred while creating the care plan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
int selectedRow = tblPatientCarePlans.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, 
        "Please select a care plan to modify first", "No Selection", JOptionPane.WARNING_MESSAGE);
    return;
}

try {
    // Get selected patient info
    String patientId = (String) tblPatientCarePlans.getValueAt(selectedRow, 0);
    CarePlanData carePlan = carePlansMap.get(patientId);

    if (carePlan == null) {
        JOptionPane.showMessageDialog(this, 
            "Unable to find care plan information", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get updated input values
    String newStartDate = txtviewCarePlanStartDate.getText().trim();
    String newResponsibleNurse = (String) CmbviewResponsibleNurse.getSelectedItem();
    String newRiskLevel = txtviewRiskLevel.getText().trim();
    String newDietaryNeeds = txtviewDietaryNeeds.getText().trim();
    String newHygieneNeeds = txtviewHygieneNeeds.getText().trim();

    // Validate input
    if (newStartDate.isEmpty() || newResponsibleNurse == null || 
        newRiskLevel.isEmpty() || newDietaryNeeds.isEmpty() || newHygieneNeeds.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Update care plan
    carePlan.setStartDate(newStartDate);
    carePlan.setResponsibleNurse(newResponsibleNurse);
    carePlan.setRiskLevel(newRiskLevel);
    carePlan.setDietaryNeeds(newDietaryNeeds);
    carePlan.setHygieneNeeds(newHygieneNeeds);

    // Refresh table
    populateCarePlansTable();

    JOptionPane.showMessageDialog(this, 
        "Care plan updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, 
        "An error occurred while updating the care plan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnExportToCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportToCSVActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save the care plan CSV file");
        fileChooser.setSelectedFile(new java.io.File("care_plans.csv"));
        
        int userChoice = fileChooser.showSaveDialog(this);
        if (userChoice == JFileChooser.APPROVE_OPTION) {
            try (FileWriter writer = new FileWriter(fileChooser.getSelectedFile())) {
                // 写入CSV头部
                writer.write("Plan ID,Patient ID,Patient Name,Start Date,Responsible Nurse,Risk Level,Dietary Needs,Hygiene Needs\n");
                
                // 写入数据
                for (CarePlanData plan : carePlansMap.values()) {
                    writer.write(String.format("%s,%s,%s,%s,%s,%s,%s,%s\n",
                        plan.getPlanId(),
                        plan.getPatient().getPatientId(),
                        plan.getPatient().getName(),
                        plan.getStartDate(),
                        plan.getResponsibleNurse(),
                        plan.getRiskLevel(),
                        plan.getDietaryNeeds(),
                        plan.getHygieneNeeds()));
                }
                
                JOptionPane.showMessageDialog(this, 
                    "CSV file exported successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, 
                    "Error while exporting CSV file:" + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportToCSVActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        int selectedRow = tblPatientCarePlans.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select the care plan you want to view first", "Not selected", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 获取选中行的数据并显示在查看区域
        String patientId = (String) tblPatientCarePlans.getValueAt(selectedRow, 0);
        CarePlanData carePlan = carePlansMap.get(patientId);
        
        if (carePlan != null) {
            txtviewPatientName.setText(carePlan.getPatient().getName());
            txtviewCarePlanStartDate.setText(carePlan.getStartDate());
            CmbviewResponsibleNurse.setSelectedItem(carePlan.getResponsibleNurse());
            txtviewRiskLevel.setText(carePlan.getRiskLevel());
            txtviewDietaryNeeds.setText(carePlan.getDietaryNeeds());
            txtviewHygieneNeeds.setText(carePlan.getHygieneNeeds());
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed
    private void clearCreateFields() {
        txtcreatePatientName.setText("");
        txtcreateCarePlanStartDate.setText("");
        txtcreateRiskLevel.setText("");
        txtcreateDietaryNeeds.setText("");
        txtcreateHygieneNeeds.setText("");
        CmbcreateResponsibleNurse.setSelectedIndex(0);
    }
    private void clearViewFields() {
        txtviewPatientName.setText("");
        txtviewCarePlanStartDate.setText("");
        txtviewRiskLevel.setText("");
        txtviewDietaryNeeds.setText("");
        txtviewHygieneNeeds.setText("");
        CmbviewResponsibleNurse.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbcreateResponsibleNurse;
    private javax.swing.JComboBox<String> CmbviewResponsibleNurse;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExportToCSV;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatientCarePlans;
    private javax.swing.JTextField txtcreateCarePlanStartDate;
    private javax.swing.JTextField txtcreateDietaryNeeds;
    private javax.swing.JTextField txtcreateHygieneNeeds;
    private javax.swing.JTextField txtcreatePatientName;
    private javax.swing.JTextField txtcreateRiskLevel;
    private javax.swing.JTextField txtviewCarePlanStartDate;
    private javax.swing.JTextField txtviewDietaryNeeds;
    private javax.swing.JTextField txtviewHygieneNeeds;
    private javax.swing.JTextField txtviewPatientName;
    private javax.swing.JTextField txtviewRiskLevel;
    // End of variables declaration//GEN-END:variables
}
